server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: hiep2004

jwt:
    signerKey: "EP0lpQrdwgRvj7bxN1/C8x1fuZEmNkNpXyNIwm/Z04r81LEhPJSpXREYFYp0R7Pr
"